### ISSUE TITLE
failed converting HotpotQA into SQuAD style

### ISSUE THREAD

**Issue by n1ghtmar4** [shmsw25/DecompRC#1]
When I used convert_hotpot2squad.py to convert HotpotQA into SQuAD style,the error 'ImportError: cannot import name 'find_span' 'would be occurred. I did not find 'find_span' in the prepro_util.py, there is only find_span_from_text

**Comment by shmsw25** [comment]
Hi @n1ghtmar4, thanks for bringing out this issue. I have fixed `convert_hotpot2squad.py` to use `find_span_from_text` instead of `find_span`. Please let me know if you encounter any other problem.

**Comment by n1ghtmar4** [comment]
Hi，a new issue. In "valuate_qa.py", line 11, can't find file "operation" to import get_answer

**Comment by shmsw25** [comment]
Thanks for pointing out the error. I have fixed the code by excluding that line.

**Comment by thakurritesh19** [comment]
Converting to squad style only works for distractor setting or in newer version of the code the same can be done for fullwiki setting ?

**Comment by shmsw25** [comment]
Hi @thakurritesh19, it is only for the distractor setting.
