### ISSUE TITLE
Comparison Code

### ISSUE THREAD

**Issue by MitchDonley** [shmsw25/DecompRC#10]
Hey,

Do you know when the comparison code will be released? I am really interested the model finds the correct span and the evidence that is uses for support.

Thank you for your work on this!

Cheers,
Mitch

**Comment by Tresfroid** [comment]
The same question, when the comparison code will be released ? Thanks!

**Comment by shmsw25** [comment]
Hi, this is the code for comparison questions: [link](https://drive.google.com/file/d/1h8B7_Qd7wUtYzvCMmlmgBQZLdTpr_f0M/view?usp=sharing)
Its README contains the instructions on how to use them. 
Thanks!

**Comment by xanhho** [comment]
Hi, thank you for your repository. You provided in [here](https://github.com/shmsw25/DecompRC#2-single-hop-rc-model) the code to run bridge and intersec questions, but I do not understand how to use it for comparison questions. Could you please provide or explain a bit about this. I have downloaded your code about comparison part and obtained three files: tokenized.json, rulebased.json, and comp.html. Thank you for your support.
