### ISSUE TITLE
Extra files in DecompRC-all-models-and-data.zip ?

### ISSUE THREAD

**Issue by ethanjperez** [shmsw25/DecompRC#2]
Thanks for the great work and for open-sourcing the code :) I'm seeing some (empty) directories in the "DecompRC-all-models-and-data.zip" file (under the "__MACOSX" directory). I'm guessing these files are unnecessary but I just wanted to confirm? Also to confirm that there aren't some files I'm missing. Thanks!

**Comment by shmsw25** [comment]
Hi @ethanjperez! Thanks for your interest in our work. For some reason I don't see `__MACOX` directory in `DecompRC-all-models-and-data`... but I guess it is an unnecessary directory.

`DecompRC-all-models-and-data` is supposed to be containing two subdirectories,  `model` and `data`, where
- `model` contains 6 directories,  `onehop` with 3 model files and 5 others with one model file each.
- `data` contains 2 directories, `decomposition-data` (with 4 json files) and `decomposed-predictions` (with 8 json files).

I just checked the zip file in Google Drive and it looks like it contains all of them, but please let me know if you have any missing file.

**Comment by ethanjperez** [comment]
Great it looks like I have all of these - thanks!
