### ISSUE TITLE
How to get the file DecompRC-all-models-and-data.zip?

### ISSUE THREAD

**Issue by clintonthomas** [shmsw25/DecompRC#4]
Thank you very much for sharing your results. Can you tell me how to get the file DecompRC-all-models-and-data.zip?

**Comment by shmsw25** [comment]
Hi @clintonthomas! Thanks for your interest in our work. As mentioned in the later section of `README.md`, it can be downloaded from [here](https://drive.google.com/file/d/1p7VrJIEmUY9tAWmx31chhStS-KoRWOJQ/view?usp=sharing).

**Comment by clintonthomas** [comment]
As a newcomer, I am honored to receive your help. Your help throws me a lot and I look forward to discussing other issues with you in the future.




------------------ 原始邮件 ------------------
发件人: "Sewon Min"<notifications@github.com>; 
发送时间: 2019年7月1日(星期一) 上午6:06
收件人: "shmsw25/DecompRC"<DecompRC@noreply.github.com>; 
抄送: "以行求知"<849334146@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [shmsw25/DecompRC] How to get the fileDecompRC-all-models-and-data.zip? (#4)




Hi @clintonthomas! Thanks for your interest in our work. As mentioned in the later section of README.md, it can be downloaded from here.

**Comment by shmsw25** [comment]
You are welcome! :)
