### ISSUE TITLE
A Question about the Paper

### ISSUE THREAD

**Issue by Simons2017** [shmsw25/DecompRC#5]
What is the difference between y_no and y_none mentioned in Section 3.3 of the paper when calculating scores?

**Comment by shmsw25** [comment]
Hi @Simons2017, thanks for your interest in our paper.
The answer on HotpotQA can be a span from the paragraph, *YES* or *NO*.
`y_no` is a logit value for "Answer is *No* according to this paragraph".
`y_none` is a logit value for "This paragraph does not have the answer (does not contain the evidence to answer the question)".

Does it make sense to you?

**Comment by Simons2017** [comment]
Oh, I see. Thank you！
