### ISSUE TITLE
predict_file

### ISSUE THREAD

**Issue by Gabriellamin** [shmsw25/DecompRC#6]
Hi,thanks for your open source code. In Decomposition Model, how does the predict_file data/decomposition-data/decomposition-bridge-dev-v1.json come? Although I know you have released the file , I want to know how do you preprocess the original data and obtain this file? Could you share the preprocess code?

**Comment by shmsw25** [comment]
Hi @Gabriellamin, thanks for your interest in our work. Data in `data/decomposition-data` are not preprocessed data - they are annotated data. We collect span annotations for question decomposition for bridge and intersection questions, and you can find details in the [original paper](https://arxiv.org/pdf/1906.02916.pdf) (in particular, Appendix A).
