### ISSUE TITLE
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

### ISSUE THREAD

**Issue by db12138** [shmsw25/DecompRC#8]
when I  run the command `python main.py --do_train --output_dir out/hotpot --train_file data/hotpot-all/train.json --predict_file data/hotpot-all/dev.json`  errors occurs : joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
Maybe it is due to different version of joblib ? Could you tell me the version of your joblib in the task? 
my joblib version is `0.14.1`

**Comment by shmsw25** [comment]
Hi @db12138, thanks for asking. My joblib version is 0.12.5.
