### ISSUE TITLE
Full wiki setting execution ?

### ISSUE THREAD

**Issue by thakurritesh19** [shmsw25/DecompRC#9]
I was able to run the code for Distractor settings however when I try to do the same for fullwiki the code expects the file dev_distractor only ?

How can I run the same for Dev_fullwiki ?

**Comment by shmsw25** [comment]
Hi @thakurritesh19, thanks for your interest. Yes, pipeline for full wiki is not included in the open-source code. However, I can explain the pipeline to you.

1. We first use [DrQA retriever](https://github.com/facebookresearch/DrQA) to retrieve top 30 paragraphs for each question based on TF-IDF scores. (Tutorials on retrieving top TF-IDF paragraphs are provided in details in DrQA repo.)
2. Using TF-IDF paragraphs, we can create a pseudo distractor data that we can use to train the model and make inference.

**Comment by thakurritesh19** [comment]
Do you have future plans of uploading the code for this ? Basically a code similar to convert_hotpot2squad.py but for converting fullwiki to squad style ?

Also, do I still need to use DrQA if hotpotqa already provides me with fullwiki dataset ? 

I am basically trying to use rest of your code as it is, but for that I need to process dev_fullwiki exactly how your code takes it. Something similar to how it is happening in distractor. If distractor anf fullwiki are exactly same JSON formatting, why does convert hotpot2squad work for only distractor and not fullwiki ?

This confusion because I think what you are trying to say is that using DrQA I can make my own data set for fullwiki , however I intend to use the one provided and then convert it to squad style.

**Comment by shmsw25** [comment]
Hi @thakurritesh19, I believe the provided HotpotQA fullwiki data is also using DrQA to retrieve top 10 paragraphs based on TF-IDF. We just found including more paragraphs (10->30) and using TF-IDF for the train data as well is more helpful in improving the performance.

If distractor and full wiki data format are identical, `hotpot2squad` should work. Where do you get an error?

**Comment by thakurritesh19** [comment]
I was getting an error in assert statements:  

        assert len(para_with_sf)>1
        assert len(contexts_list)>1

Post commenting these, hotpot_fullwiki was successfully converted to squad style as well like distractor setting. 

However do you think that would be an issue ?

I was going through the description as to what fullwiki setting is and decided that those two assert statements weren't needed for fullwiki -> squad style conversion. 

I am as of now running single hop RC. If I see any issue I will post it here.

Many Thanks.

**Comment by thakurritesh19** [comment]
> Hi @thakurritesh19, I believe the provided HotpotQA fullwiki data is also using DrQA to retrieve top 10 paragraphs based on TF-IDF. We just found including more paragraphs (10->30) and using TF-IDF for the train data as well is more helpful in improving the performance.
> 
> If distractor and full wiki data format are identical, `hotpot2squad` should work. Where do you get an error?

Where are you doing this "We just found including more paragraphs (10->30) and using TF-IDF for the train data as well is more helpful in improving the performance." ?

**Comment by shmsw25** [comment]
Hi @thakurritesh19,
> I was getting an error in assert statements:

Got it, so I think it is fine to delete these assertions for full wiki setting, because they only matter on the train data.

> We just found including more paragraphs (10->30) and using TF-IDF for the train data as well is more helpful in improving the performance.

This is not part of code because it's for full wiki setting.

**Comment by thakurritesh19** [comment]
> Hi @thakurritesh19,
> 
> > I was getting an error in assert statements:
> 
> Got it, so I think it is fine to delete these assertions for full wiki setting, because they only matter on the train data.
> So if I removed those, would it cause any issue in training ? I still see the code running but I am worried if it will cause me some accuracy.

Also I would have wanted to convert train file with those statements and then remove them for fullwiki but it converts both the files at once and not like you can convert one first and second later.

> > We just found including more paragraphs (10->30) and using TF-IDF for the train data as well is more helpful in improving the performance.
> 
> This is not part of code because it's for full wiki setting.

**Comment by thakurritesh19** [comment]
I see the code only evaluates on the basis of F1 scores. The final results I got using show_result.py using pretty table are only F1 scores right ?

Is there a scope to print EM scores too ?

**Comment by shmsw25** [comment]
I don't think so, sorry. But you can modify [this line](https://github.com/shmsw25/DecompRC/blob/master/DecompRC/show_result.py#L10) to `from hotpot_evaluate_v1 import f1_score, exact_match_score` and replace `f1_score` to `exact_match_score` in order to print the exact match score instead of F1 score.
